# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main

pool:
  name: Default
  vmImage: 'agent1-linux'

variables:
  project: 'CmswebApI/CmswebApI.csproj'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(project)'
  displayName: 'Restore NuGet packages'

- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Publish Project'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    modifyOutputPath: true
    zipAfterPublish: true

- task: PublishPipelineArtifact@1
  displayName: 'Publish artifact'
  inputs:
    artifactName: 'my-artifact'
    targetPath: '$(Build.ArtifactStagingDirectory)'
