# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: '**/*.csproj'
  buildConfiguration: 'Debug'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(project)'
  displayName: 'Restore NuGet packages'

- task: SonarCloudPrepare@1
  displayName: "Sonar - Prepare Analysis"
  inputs:
    SonarCloud: 'Sonar Cloud'
    organization: 'singhdivya-2895'
    scannerMode: 'MSBuild'
    projectKey: 'dotnetcore-learning'
    projectName: 'DotnetCore Learning'
    extraProperties: |
      sonar.cs.opencover.reportsPaths;=$(Build.SourcesDirectory)/TestResults/Coverage/coverage.opencover.xml,$(Build.SourcesDirectory)/TestResults/Coverage/coverage.cobertura.xml

- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Install ReportGenerator'
  inputs:
    command: custom
    custom: tool
    arguments: 'install --global dotnet-reportgenerator-globaltool'

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    arguments: '--no-build --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat="cobertura%2copencover" /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
    publishTestResults: true
    projects: '**/*Test.csproj'

- task: SonarCloudAnalyze@1
  displayName: "Sonar - Run Code Analysis"

- task: SonarCloudPublish@1
  displayName: "Sonar - Publish Quality Gate Results"
  inputs:
    pollingTimeoutSec: '300'

- script: |
    reportgenerator -reports:$(Build.SourcesDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:HtmlInline_AzurePipelines
  displayName: 'Create code coverage report'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'

- task: DotNetCoreCLI@2
  displayName: 'Publish Project'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    modifyOutputPath: true
    zipAfterPublish: true

- task: PublishPipelineArtifact@1
  displayName: 'Publish artifact'
  inputs:
    artifactName: 'my-artifact'
    targetPath: '$(Build.ArtifactStagingDirectory)'
